services:
  fastapi:
    restart: always
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8000
        published: 8000
    env:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    #deploy:
    #  resources:
    #    reservations:
    #      memory: 256M
